version: "3.8"
services:
  lince-discord-bot:
    build: .
    image: multithefranky/lince-discord-bot
    platform: linux/amd64
    container_name: lince-discord-bot
    volumes:
      - "./log:/log"
      - "./db:/db"
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
